/*
 * Copyright 2024 Inclusive Design Research Centre, OCAD University
 * All rights reserved.
 *
 * Licensed under the New BSD license. You may not use this file except in
 * compliance with this License.
 *
 * You may obtain a copy of the License at
 * https://github.com/inclusive-design/adaptive-palette/blob/main/LICENSE
 */
import { JsonPaletteType } from "./index.d";

/**
 * Global Utility Functions
 */

/**
 * Generate the grid css.
 * @param {number} columnStart - The number of the column that the grid item will start from.
 * @param {number} columnSpan - The number of columns that the item will span across.
 * @param {number} rowStart - The number of the row that the grid item will start from.
 * @param {number} rowSpan - The number of rows that the item will span across.
 * @return {String} - The grid css.
 */
function generateGridStyle(columnStart: number, columnSpan: number, rowStart: number, rowSpan: number): string {
  return `grid-column: ${columnStart} / span ${columnSpan};grid-row: ${rowStart} / span ${rowSpan};`;
}

/**
 * Use the text-to-speech to announce the given text. If the previous announcement is still going
 * on, cancel it.
 * @param {String} text - The text to be announced.
 */
function speak(text): void {
  // If the text-to-speech feature is unavailable, do nothing. This happens when running node tests.
  if (!window.speechSynthesis) {
    return;
  }

  // Cancel the previous announcement
  if (window.speechSynthesis.speaking || window.speechSynthesis.pending) {
    window.speechSynthesis.cancel();
  }
  // Announce the current text
  const utterThis = new SpeechSynthesisUtterance(text);
  window.speechSynthesis.speak(utterThis);
}

/**
 * Import a palette from the given JSON file using dynamic `import()`.
 * The location of the JSON file is provided as a variable.
 * See https://vitejs.dev/guide/features.html#dynamic-import
 *
 * @param {String} jsonFilePath - Path of the JSON file to load, without the
 *                                ".json" extension (added herein).
 * @return {JsonPaletteType}    - The palette itself, or `null` if it could not be
 *                                loaded.
 */
async function importPaletteFromJsonFile (jsonFilePath: string): Promise<JsonPaletteType> {
  // The "@vite-ignore" comment is used to suppress a warning generated by Vite during
  // dynamic imports analysis. This warning is reported when both the file path and the
  // filename are provided in a single variable. Using one sigle file location variable
  // enhances the clarity and maintainability of the code, so this comment serves to
  // mitigate the warning while ensuring the code remains sensible.
  // Note: the file extension ".json" needs to be concatenated separately for the dynamic
  // import of JSON files to work properly.
  // See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations
  // for supported dynamic import formats.
  const paletteJson = await import(/* @vite-ignore */`${jsonFilePath}.json`);
  return paletteJson;
}

export {
  generateGridStyle,
  speak,
  importPaletteFromJsonFile
};
